---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/OpenStructUse:
  Exclude:
    - test/**/*.rb
